#!/bin/sh

set -e

lb config noauto \
  --apt aptitude \
  --architectures amd64 \
  --archive-areas "main contrib non-free" \
  --binary-filesystem fat32 \
  --bootappend-install "locales=en_US UTF-8" \
  --bootappend-live "locales=en_US.UTF-8" \
  --checksums sha1 \
  --debian-installer live \
  --debian-installer-distribution sid \
  --distribution sid \
  --firmware-binary false \
  --firmware-chroot false \
  --mirror-bootstrap "http://http.us.debian.org/debian/" \
  --mirror-binary "http://http.us.debian.org/debian/" \
  --mirror-chroot "http://http.us.debian.org/debian/" \
  --mirror-debian-installer "http://http.us.debian.org/debian/" \
  --mode "debian" \
  --parent-archive-areas "main contrib non-free" \
  --parent-distribution sid \
  --parent-debian-installer-distribution sid \
  --parent-mirror-bootstrap "http://http.us.debian.org/debian/" \
  --parent-mirror-binary "http://http.us.debian.org/debian/" \
  --parent-mirror-chroot "http://http.us.debian.org/debian/" \
  --parent-mirror-debian-installer "http://http.us.debian.org/debian/" \
  --system live \
  "${@}"
