#!/bin/sh

set -e

lb config noauto \
  --apt aptitude \
  --architectures amd64 \
  --archive-areas "main contrib non-free" \
  --debian-installer live \
  --debian-installer-distribution sid \
  --debootstrap-options "--exclude sysvinit --include systemd,systemd-sysv" \
  --distribution sid \
  --firmware-binary false \
  --firmware-chroot false \
  --initsystem systemd \
  --mirror-bootstrap "http://ftp.de.debian.org/debian/" \
  --mirror-binary "http://ftp.de.debian.org/debian/" \
  --mirror-chroot "http://ftp.de.debian.org/debian/" \
  --mirror-debian-installer "http://ftp.de.debian.org/debian/" \
  --system live \
  "${@}"
